version: "3.9"
services:

  tun2socks:
    container_name: tun2socks
    hostname: tun2socks
    build:
      context: build
      dockerfile: Dockerfile
    image: registry.home.local/tun2socks:latest
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    environment:
      - LOGLEVEL=info # default
      - TUN=tun0 # default
      - ADDR=198.18.0.1/15 # default
      - MTU=9000 # default
      - PROXY=192.168.1.80:1080 # *required
      - STATS=:8080 # optional
      - RESTAPI= # optional
      - TCP_SNDBUF= # optional
      - TCP_RCVBUF= # optional
      - TCP_AUTO_TUNING= # optional
      - UDP_TIMEOUT= # optional
      - EXTRA_COMMANDS= # optional
      - TUN_INCLUDED_ROUTES= # optional
      - TUN_EXCLUDED_ROUTES= #optional
      # - GODEBUG=madvdontneed=1  # optional 
    sysctls:
      - net.ipv4.ip_forward=1
      # - net.ipv4.conf.all.rp_filter=0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 256m
    memswap_limit: 256m
    mem_reservation: 256m

  wireguard:
    container_name: wireguard
    hostname: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000                     
      - PGID=1000                     
      - TZ=Etc/UTC                    
      - SERVERURL=192.168.1.82      
      - PEERDNS=false                  
      - INTERNAL_SUBNET=10.9.1.0 
      - ALLOWEDIPS=0.0.0.0/0          
      - PERSISTENTKEEPALIVE_PEERS=    
      - LOG_CONFS=true                
      - PEERS=1             
      - TUNNEL_GW=tun2socks
      - ROUTE_TABLE=250
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    volumes:
      - ./custom-cont-init.d:/custom-cont-init.d
      - ./config:/config:z
      - /lib/modules:/lib/modules:z
    ports:
      - 51820:51820/udp
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 512m
    memswap_limit: 512m
    mem_reservation: 512m
